### PR TITLE
Product Image Field Setting

### PR DESCRIPTION
**Pull request by smockensturm**
- add a product image field and transform to settings.
- get the url in the payload

copped a few bits from `@FosterCommerce/klaviyoconnect`

### CODE REVIEW

**Comment by smockensturm** [comment]
Bumped. Any interest?

**Comment by engram-design** [comment]
After noting continued edits to your PR, just wanted to wait until you were finalised. Ready for review now?

**Comment by smockensturm** [comment]
ok sure

**Comment by engram-design** [comment]
Thanks for this, I've just merged this, but having a final review, I'm not sure if it's working as you'd expect?

For instance, these lines do nothing 

https://github.com/verbb/stamped-io/blob/f3c32bc7788ccc52aa7da6d3b12f3f4d0332d088/src/services/Service.php#L95-L103

Because `$lineItemProperties` is never used.

**Comment by engram-design** [comment]
I've just pushed a [number of changes](https://github.com/verbb/stamped-io/commits/craft-3) which have iterated on yours.

- Change Product Image to select. Otherwise users can put any text in the field, producing errors when trying to access a field that either isn't an Assets field, or doesn't exist.
- Ensure that we only fetch the image if this setting is set. Otherwise, more errors. For example, trying to do `$variant->''` (if you didn't enter a value it would be an empty string `''`)
- Similar for Image Transforms (renamed from Transformation), a select where users can pick existing transforms. Errors will be thrown if providing text that isn't a transform. For example, trying to do `$image->getUrl('', true)` (if you didn't enter a value it would be an empty string `''`)
- Fix the use of `$lineItemProperties`, should be `$imageUrl`, which is used in the `$payload` sent to Stamped.

I've also made a few improvements, not related to this regarding using `.env` variables for settings, and some cleanup.

**Comment by smockensturm** [comment]
eh thanks for the help and edification. rushed as you may well have deduced.

**Comment by smockensturm** [comment]
> I've just pushed a [number of changes](https://github.com/verbb/stamped-io/commits/craft-3) which have iterated on yours.
> 
>     * Change Product Image to select. Otherwise users can put any text in the field, producing errors when trying to access a field that either isn't an Assets field, or doesn't exist.
> 
>     * Ensure that we only fetch the image if this setting is set. Otherwise, more errors. For example, trying to do `$variant->''` (if you didn't enter a value it would be an empty string `''`)
> 
>     * Similar for Image Transforms (renamed from Transformation), a select where users can pick existing transforms. Errors will be thrown if providing text that isn't a transform. For example, trying to do `$image->getUrl('', true)` (if you didn't enter a value it would be an empty string `''`)
> 
>     * Fix the use of `$lineItemProperties`, should be `$imageUrl`, which is used in the `$payload` sent to Stamped.
> 
> 
> I've also made a few improvements, not related to this regarding using `.env` variables for settings, and some cleanup.

Hey. Just wanted to let you know none of these changes ever made it into the latest Craft 3 package / release (1.0.1)

**Comment by engram-design** [comment]
@smockensturm Released [1.0.2](https://github.com/verbb/stamped-io/releases/tag/1.0.2)

**Pull request merged**
